admin_access/urls.py
from django.urls import path

from . import views

app_name = 'admin_access'

urlpatterns = [
  path('', views.admin_list, name='aa_list'),
  path ('new', views.admin_create, name='project_new'),
  path ('edit/<int:pk>', views.admin_update, name='project_edit'),
  path ('delete/<int:pk>', views.admin_delete, name='project_delete'),

]

datascicences/urls.py
from django.urls import include, path
from django.contrib import admin


from workflow import views

urlpatterns = [
    path ('accounts/', include ('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('student_access/', include('student_access.urls', namespace='student_access')),
    #path('student_access/login/', include ('student_access.urls', namespace='login')),
    path('professor_access/', include('professor_access.urls', namespace='professor_access')),
    path('admin_access/', include('admin_access.urls', namespace='admin_access')),
    path('', views.home),
    path('login/', views.login),
    path ('logout/', views.login),
    path('register/', views.register),

]

professor_access/urls.py
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings


from . import views


app_name = 'professor_access'

urlpatterns = [
  path ('', views.professor_list, name='pa_list'),
  #path ('1', views.student_list, name='sa_list'),
  path ('new', views.professor_create, name='project_new'),
  #path ('edit/<int:pk>', views.professor_update, name='project_edit'),
  # path ('projects', views.projects, name='projects'),
  path ('detail/<int:pk>', views.detail, name='detail'),
  #path ('detail2/<int:pk>', views.detail2, name='detail2'),
  path ('files', views.files, name='files'),
  path ('upload/<str:filename>', views.upload, name='upload'),
  #path ('mdeditor', include ('mdeditor.urls'))
  #path ('ckeditor/', include('ckeditor_uploader.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student_access/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'student_access'

urlpatterns = [
  path ('', views.student_list, name='sa_list'),
  #path ('1', views.student_list, name='sa_list'),
  path ('detail/<int:pk>', views.detail, name='detail'),
  #path ('detail2/<int:pk>', views.detail2, name='detail2'),
  #path ('login/', views.student_login, name='login'),
  #path ('login/', auth_views.LoginView.as_view (), name='login'),
  #path ('logout/', auth_views.LogoutView.as_view (), name='logout'),
  #path ('', views.dashboard, name='dashboard'),
  #path ('', views.user_login, name='login'),

]

workflow/models.py
from django.contrib.auth.models import AbstractUser, User
from django.db import models


class UserProfile (models.Model):
    ROLE_CHOICES = (
        ('student', 'student'),
        ('professor', 'professor'),
        ('admin', 'admin'),
    )

    user = models.OneToOneField (User, blank=True, null=True, on_delete=models.CASCADE, related_name='profile')
    role = models.CharField (max_length=20, choices=ROLE_CHOICES, default='student')

    def __str__(self):
        return f'{self.user}_{self.role}'

def get_role(user):
    if hasattr (user, 'profile'):
        return user.profile.role
    return ''

workflow/forms.py
from django import forms
from django.contrib.auth.models import User

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password',
                               widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password',
                                widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']

workflow/views.py
from django.contrib import auth
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import render

from workflow.models import UserProfile

from .forms import UserRegistrationForm

def home(request):
    for user in User.objects.all ():
        if not hasattr (user, 'profile'):
            UserProfile.objects.create (user=user)
    return render (request, "home.html")

def login(request):
    if request.method == 'POST':
        username = request.POST.get ('username')
        password = request.POST.get ('password')
        user = auth.authenticate (username=username, password=password)
        if user is not None and user.is_active:
            auth.login (request, user)
            url = f'/{user.profile.role}_access/'
            return HttpResponseRedirect (url)
        else:
            msg = 'Invalid password'

    return render (request, "login.html", locals ())


def register(request):
    if request.method == 'POST':
        username = request.POST.get ('username')
        password1 = request.POST.get ('password1')
        password2 = request.POST.get ('password2')


        #role = request.POST.get ('role')
        #professor_id = request.POST.get ('professor_id')
        if password1 != password2:
            msg = 'Two password not match'
        elif User.objects.filter (username=username).exists ():
            msg = 'The username is exists'
        else:
            u = User.objects.create (username=username)
            u.set_password (password1)
            u.save ()
            profile = UserProfile.objects.create (user=u)
         #   profile.role = role
         #   if role == 'student':
         #       profile.professor_id = professor_id
            profile.save ()
            return HttpResponseRedirect ('/login/')

    professors = User.objects.filter (profile__role='professor').all ()

    return render (request, "register.html", locals ())

workflow/templates/base.html
{% load staticfiles %}
<head>
    <title>UNO Math Department | {{ request.user }} {{ request.user.profile.role }}</title>
    <style>
    body {
        font-family: Arial, Helvetica, sans-serif;
        /*background-color: #eee;*/
        background-color:white;
    }
    {
        color:black;
	    text-decoration: none;
    }
 /* a:hover {
        color:grey;
    }
    */
    .title {
        margin-top:30px;
        margin-bottom:30px;
        font-family:"Helvetia Neue","Helvetica";
        float:left;
        line-height:20px;
        text-size-adjust:100%;
        font-size:50px;
        font-weight:bold;
        text-indent:170px;
    }

    #subtitle {
        margin-top:80px;
        margin-bottom:30px;
        float:center;
        font-family:"Helvetia Neue","Helvetica";
        text-indent:350px;
        font-size:25px;
        line-height:60px;
        font-weight:none;


    }

    .login {
        width:1024px;
        height:400px;
        font-size:18px;
        line-height:40px;
        margin:auto;
        display:flex;
        flex-direction:row;
    }

     .login1 {
        width:400px;
        height:280px;
        font-size:18px;
        line-height:0px;
        margin:40px 40px;
        background-color:#eee;
        float:center;
        text-align:center;
        line-height:20px;
    }
    .login2{
        width:1024px;
        height:200px;
        text-align:left;
        text-indent:60px;
        margin:auto;

    }
    .p3 {
        font-size:14px;
        text-align:center;
        text-indent: 100px;
    }
    .span{
        position:relative;
        left:180px;
    }
    .img{
        width:200px;
        height:205px;
        margin-top:20px;
    }

   .box{
        width:1030px;
        height:151px;
        border-color:#eee;
        background-color:#eee;
        border-style:none;
        margin:30px auto;
        padding:30px 15px;

    }
    #log_des{
        width:1030px;
        height:20px;
        margin:auto;
        font-size:20px;
    }
    .footer{
        width:1030px;
        height:151px;
        margin:30px auto;
        text-align:left;
        font-size:16px;
        }


    input,select{
        outline-style: none ;
        border: 1px solid #ccc;
        border-radius: 3px;
        padding: 10px;
        width: 200px;
    }

    input[type=checkbox]{
        width: auto;
    }

    input:focus,select:focus{
        border-color: #66afe9;
        outline: 0;
        -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075),0 0 8px rgba(102,175,233,.6);
        box-shadow: inset 0 1px 1px rgba(0,0,0,.075),0 0 8px rgba(102,175,233,.6)
    }

    .register_des{
        background-color:red;
        float:left;
    }
    .box_register{
        width:1030px;
        height:500px;
        border-style:none;
        margin:30px auto;
        padding:30px 15px;
    }
    #log_des1 {
        font-size:30px;
    }
   </style>
</head>
    <!--<div class="box"><a class= "title" href="/" >Project Management System</a>
        <div id="subtitle"><a href="/">UNO Math Data Consulting Lab</a></div>
    </div>-->
    <div class="box"><a class= "title">Project Management System</a>
        <div id="subtitle">UNO Math Data Consulting Lab</div>
    </div>

    <div>
        {% block content %}
        {% endblock %}
    </div>
﻿
    <div class="footer">
        <hr />
        <p>Copyright &copy;2019 UNO Math Department, Data and Decision Sciences Group</p>
        Data Consulting Lab,
        6001 Dodge Street Omaha, NE 68182-0243
        Email: xycheng@unomaha.edu
    </div>


</body>
</html>

workflow/templates/home.html
{% extends "base.html" %}
{% load staticfiles %}

<head>
    <title>UNO Math Department</title>

</head>

<body>

<div>{% block content %}
  <!--<p id="log_des">Welcome to the Project Management System, please choose from below options to login.</a></p>-->
  <p id="log_des">Welcome to the Project Management System, please <a href="/login/">login</a> or <a href="/register/">Register</a> your account.</p>

    <!--<div class ="login">
    <div class="login1">﻿
      <a href="{% url 'student_access:sa_list' %}">
        <img class="img" src="/static/images/student.png"/><br /><br />
        Login - Student Assistant
      </a>
    </div>
    <div class="login1">
      <a href="{% url 'professor_access:pa_list' %}">
        <img class="img" src="/static/images/advisor.png" /><br /><br />
        Login - Advisor
      </a>
    </div>
    <div class="login1">
    <a href="/admin/">
    <img class="img" src="/static/images/admin.png"/><br /><br />
        Login - Admin
      </a>
    </div>
</div>-->

{% endblock %}
</div>
</body>
</html>

workflow/templates/login.html
{% extends "base.html" %}
{% load staticfiles %}

<head>
    <title>UNO Math Department</title>

</head>

<body>
{% block content %}
<p id="log_des" style="text-align: center">Login to Website</p>
<div class ="login">

  <form method="post" style="text-align: center; width: 100%; margin: 20px">
    {% csrf_token %}
    <p>
      Username: <input type="text" name="username">
    </p>
    <!--<p>
      Email: <input type="text" name="email">
    </p>--->
    <p>
      Password: <input type="password" name="password">
    </p>
    <p>
      <input type="submit" value="Sign In">
    </p>
  </form>
</div>

  <script>
    {% if msg %}
        alert('{{ msg }}')
    {% endif %}
  </script>

{% endblock %}
</body>
</html>

workflow/templates/register.html
{% extends "base.html" %}
{% load staticfiles %}

<head>
    <title>UNO Math Department</title>

</head>

<body>
{% block content %}
<div class="box_register"><p id="log_des1" style="text-align: center">Create an account </p>
<div class ="login">
  <form method="post" style="text-align: center; width: 100%; margin: 20px">
    {% csrf_token %}
      <p style="text-align: center">Please, sign up using the following form:</p>
    <p>
      <span style="display: inline-block; width: 300px">Username:
      <input type="text" name="username"> </span>
    </p>
     <p>
      <span style="display: inline-block; width: 300px">Email:
      <input type="text" name="username"> </span>
    </p>
    <!--<p>
      <span style="display: inline-block; width: 300px">Role
      <select name="role">
        <option value="student">student</option>
        <option value="professor">professor</option>
        <option value="admin">admin</option>
      </select></span>
    </p>
    <p class="professor_select">
      <span style="display: inline-block; width: 300px">Professor（if you are a student）
      <select name="professor_id">
        {% for professor in professors %}
          <option value="{{ professor.id }}">{{ professor.username }}</option>
        {% endfor %}
      </select></span>
    </p>-->
    <p>
      <span style="display: inline-block; width: 300px">Password:
      <input type="password" name="password1">
    </span>
    </p>

    <p>
      <span>Repeat Password:
      <input type="password" name="password2"></span>

    </p>

    <p>
	<div class="submit">
		<input class="submit" type="submit" value="CREATE MY ACCOUNT">
	</div>
    </p>
  </form>
</div>
</div>

  <script>
    {% if msg %}
        alert('{{ msg }}')
    {% endif %}
  </script>

{% endblock %}
</body>
</html>