admin_access/urls.py
from django.urls import path

from . import views

app_name = 'admin_access'

urlpatterns = [
  path('', views.admin_list, name='aa_list'),
  path ('new', views.admin_create, name='project_new'),
  path ('edit/<int:pk>', views.admin_update, name='project_edit'),
  path ('delete/<int:pk>', views.admin_delete, name='project_delete'),

]

datascicences/urls.py
from django.urls import include, path
from django.contrib import admin


from workflow import views

urlpatterns = [
    path ('accounts/', include ('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('student_access/', include('student_access.urls', namespace='student_access')),
    #path('student_access/login/', include ('student_access.urls', namespace='login')),
    path('professor_access/', include('professor_access.urls', namespace='professor_access')),
    path('admin_access/', include('admin_access.urls', namespace='admin_access')),
    path('', views.home),
    path('login/', views.login),
    path ('logout/', views.login),
    path('register/', views.register),

]

student_access/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'student_access'

urlpatterns = [
  path ('', views.student_list, name='sa_list'),
  #path ('1', views.student_list, name='sa_list'),
  path ('detail/<int:pk>', views.detail, name='detail'),
  #path ('detail2/<int:pk>', views.detail2, name='detail2'),
  #path ('login/', views.student_login, name='login'),
  #path ('login/', auth_views.LoginView.as_view (), name='login'),
  #path ('logout/', auth_views.LogoutView.as_view (), name='logout'),
  #path ('', views.dashboard, name='dashboard'),
  #path ('', views.user_login, name='login'),

]

student_access/models.py
#from django.db import models
#from django.urls import reverse


#class Project(models.Model):
#    name = models.CharField(max_length=50)
#    advisor = models.CharField(max_length=200)
#    stage = models.CharField(max_length=50)
#    description = models.TextField(blank=True)
#    note = models.TextField(blank=True)
#    def __str__(self):
#        return str(self.name)

student_access/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import ModelForm
from django.contrib.auth import authenticate, login
from django.http import HttpResponse
from professor_access.models import Project
from workflow.models import get_role
from .forms import LoginForm
from django.contrib.auth.decorators import user_passes_test


def student_required(function):
    actual_decorator = user_passes_test(
        lambda u: get_role(u) == 'student',
        login_url='/login/'
    )
    return actual_decorator(function)


@student_required
def dashboard(request):
    return render(request,
                  'student_access/dashboard.html',
                  {'section': 'dashboard'})


@student_required
def student_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request,
                                username=cd['username'],
                                password=cd['password'])
            if user:
                login(request, user)
                return redirect("student_access:sa_list")
            else:
                return HttpResponse('Disabled account')
        else:
            return HttpResponse('Invalid login')
    elif request.method == 'GET':
        form = LoginForm ()
        context = {'form': LoginForm}
        return render (request, 'student_access/login.html', context)
    else:
        return HttpResponse ("Use GET to requrest data")


class studentForm(ModelForm):
    class Meta:
        model = Project
        fields = ['id','name', 'advisor', 'stage']


@student_required
def student_list(request, template_name='student_access/sa_list.html'):
    project = Project.objects.filter(users=request.user)
    data = {}
    data['object_list'] = project
    return render(request, template_name, data)


@student_required
def detail(request, pk, template_name='student_access/detail.html'):
    project = get_object_or_404(Project, pk=pk)
    if request.method == 'POST':
        name = request.POST['name']
        stage = request.POST['stage']
        #description = request.POST['description']
        note = request.POST['note']
        project.name = name
        project.stage = stage
        #project.description = description
        project.note = note
        project.save()
        return redirect('student_access:sa_list')

    return render(request, template_name, locals())

student_access/templates/student_access/dashboard.html
{% extends "base.html" %}

{% block title %}Dashboard{% endblock %}

{% block content %}
  <h1>Dashboard</h1>
  <p>Welcome to the dashboard.</p>
{% endblock %}

student_access/templates/student_access/detail.html
{% extends "base.html" %}

{% block content %}
<html>
<header>
<style>
	.box{
        display: none;

    }
     #subtitle {
        display: none;
    }
    a {
        color:black;
	    text-decoration: none;
    }

    a:hover {
        color:grey;
    }
    .box1{
        width:1030px;
        height:151px;
        border-color:#eee;
        background-color:#eee;
        border-style:none;
        margin:30px auto;
        padding:30px 15px;

    }
     #subtitle1{
        margin-top:80px;
        margin-bottom:30px;
        float:center;
        font-family:"Helvetia Neue","Helvetica";
        text-indent:350px;
        font-size:25px;
        line-height:60px;
        font-weight:none;


    }
	.input{
		display: none;
	}
	.submit{
		display: none;
	}
	.back_button{
		text-align:right;
		font-size:18px;

	}
	.content_s{
		width:1030px;
		margin: 10px auto;
		padding:10px;
	}
	.prj_name{
		text-align:center;
		font-size:25px;
		font-weight:bold;
	}
	.professor_name{
		text-align:center;
		font-size:18px;
	}
	.text{
		 font-size:18px;
		 line-height: 2.5;
	}
	.name{
		font-size:20px;
		font-weight:bold;
	}

	.student_name{
		text-align:center;
		font-size:18px;
	}
	.advisor_assistant{
		font-size:20;
		font-weight:bold;

	}
</style>
</header>
<body>
    <div class="box1"><a class= "title" href="/student_access/" >Project Management System</a>
        <div id="subtitle1"><a href="/student_access/">UNO Math Data Consulting Lab</a></div>
    </div>
<div class="content_s">
<div class="back_button"><a href="/logout/">Logout</a></div>

<form method="post">{% csrf_token %}

	<p>
		<div class="prj_name">{{project.name}}</div>
		<span class="input"><input type="text" name="name" value="{{project.name}}"></span>
	</p>

	<div class="student_name">
		<span class="advisor_assistant">Professors: </span>
    {% for professor in project.professors %}
      {% if forloop.counter != 1 %},{% endif %}
      {{ professor.username }}
    {% endfor %}
	</div>

	<div class="student_name">
		<span class="advisor_assistant">Students: </span>
    {% for student in project.students %}
      {% if forloop.counter != 1 %},{% endif %}
      {{ student.username }}
    {% endfor %}
	</div>

	<!--<p class="name">Content</p>
		<span class="text">{{project.description|safe|linebreaksbr}}</span>
		<span class="input"><textarea cols="40" rows="5" name="description">{{project.description}}</textarea></span>
-->

	<p>
		<p class="name">Content</p>
		<span class="text">{{project.note|safe|linebreaksbr}}</span>
		<span class="input"><textarea cols="40" rows="5" name="note">{{project.note}}</textarea></span>
	</p>
		<p class="name">
		Stage
		<span class="text">{{project.stage}} <button type="button" class="edit">edit</button></span>
		<span class="input"><input type="text" name="stage" value="{{project.stage}}"></span>
	</p>
	<p>
		<input class="submit" type="submit" value="submit">
	</p>
</form>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script>
	$('.edit').click(function(){
		$(this).parent().parent().find('.text').hide()
		$(this).parent().parent().find('.input').show()
		$('.submit').show()
	})
</script>
</div>
{% endblock %}
</body>
</html>

student_access/templates/student_access/login.html
{% extends "base.html" %}

{% block title %}Log-in{% endblock %}

{% block content %}
  <h1>Log-in</h1>
  {% if form.errors %}
    <p>
      Your username and password didn't match.
      Please try again.
    </p>
  {% else %}
    <p>Please, use the following form to log-in:</p>
  {% endif %}

  <div class="login-form">
    <form action="{% url 'login' %}" method="post">
      {{ form.as_p }}
      {% csrf_token %}
      <input type="hidden" name="next" value="{{ next }}" />
      <p><input type="submit" value="Log-in"></p>
    </form>
  </div>>
{% endblock %}

student_access/templates/student_access/sa_list.html
{% extends "base.html" %}

{% block content %}

<!--<a href="{% url 'student_access:sa_list' %}">Student Access</a>-->

<head>
    <title>Projects</title>
    <style>
    body {
        background-color: white;
        font-family: Arial, Helvetica, sans-serif;
    }
    .box{
        display: none;

    }
     #subtitle {
        display: none;
    }
    a {
        color:black;
	    text-decoration: none;
    }

    a:hover {
        color:grey;
    }
    .box1{
        width:1030px;
        height:151px;
        border-color:#eee;
        background-color:#eee;
        border-style:none;
        margin:30px auto;
        padding:30px 15px;

    }
     #subtitle1{
        margin-top:80px;
        margin-bottom:30px;
        float:center;
        font-family:"Helvetia Neue","Helvetica";
        text-indent:350px;
        font-size:25px;
        line-height:60px;
        font-weight:none;


    }
        .table {
            width:1030px;
            margin: left;
            /*border:2px solid black;
            border-spacing:0px;*/
            border-collapse: collapse;
            background-color:lightgrey;
            font-size:16px;
            line-height: 35px;
            margin: 30px auto;
            text-indent:10px;
                }

        td,th {
		    border:2px solid black;
	           }

	    tr:nth-child(odd){
	     background-color:white;
	            }

        tr:hover{
            background-color:darkgrey;
                }

        .hello1{
            font-size:20px;
            width:1030px;
            margin: 10px auto;
                }

   </style>
</head>

<body>
    <div class="box1"><a class= "title" href="/student_access/" >Project Management System</a>
        <div id="subtitle1"><a href="/student_access/">UNO Math Data Consulting Lab</a></div>
    </div>
<p class="hello1">Welcome to the Project Management System, there are some information about your project.</p>
<table class="table">
    <thead>
    <tr>
        <th>Project ID</th>
        <th>Project Name</th>
        <th>Advisor</th>
        <th>Stage</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>
    {% for project in object_list %}
    <tr>
        <td>{{ project.id}}</td>
        <td>{{ project.name }}</td>
        <td>{{ project.advisor }}</td>
        <td>{{ project.stage }}</td>
        <td><a href="{% url 'student_access:detail' project.id %}">Detail</a>
    </tr>
    {% endfor %}
    </tbody>
</table>
</body>

{% endblock %}