admin_access/urls.py
from django.urls import path

from . import views

app_name = 'admin_access'

urlpatterns = [
  path('', views.admin_list, name='aa_list'),
  path ('new', views.admin_create, name='project_new'),
  path ('edit/<int:pk>', views.admin_update, name='project_edit'),
  path ('delete/<int:pk>', views.admin_delete, name='project_delete'),

]

datascicences/urls.py
from django.urls import include, path
from django.contrib import admin


from workflow import views

urlpatterns = [
    path ('accounts/', include ('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('student_access/', include('student_access.urls', namespace='student_access')),
    #path('student_access/login/', include ('student_access.urls', namespace='login')),
    path('professor_access/', include('professor_access.urls', namespace='professor_access')),
    path('admin_access/', include('admin_access.urls', namespace='admin_access')),
    path('', views.home),
    path('login/', views.login),
    path ('logout/', views.login),
    path('register/', views.register),

]

professor_access/urls.py
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings


from . import views


app_name = 'professor_access'

urlpatterns = [
  path ('', views.professor_list, name='pa_list'),
  #path ('1', views.student_list, name='sa_list'),
  path ('new', views.professor_create, name='project_new'),
  #path ('edit/<int:pk>', views.professor_update, name='project_edit'),
  # path ('projects', views.projects, name='projects'),
  path ('detail/<int:pk>', views.detail, name='detail'),
  #path ('detail2/<int:pk>', views.detail2, name='detail2'),
  path ('files', views.files, name='files'),
  path ('upload/<str:filename>', views.upload, name='upload'),
  #path ('mdeditor', include ('mdeditor.urls'))
  #path ('ckeditor/', include('ckeditor_uploader.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student_access/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'student_access'

urlpatterns = [
  path ('', views.student_list, name='sa_list'),
  #path ('1', views.student_list, name='sa_list'),
  path ('detail/<int:pk>', views.detail, name='detail'),
  #path ('detail2/<int:pk>', views.detail2, name='detail2'),
  #path ('login/', views.student_login, name='login'),
  #path ('login/', auth_views.LoginView.as_view (), name='login'),
  #path ('logout/', auth_views.LogoutView.as_view (), name='logout'),
  #path ('', views.dashboard, name='dashboard'),
  #path ('', views.user_login, name='login'),

]

professor_access/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone


# from mdeditor.fields import MDTextField
# from ckeditor.fields import RichTextField
# from tinymce.models import HTMLField
# from ckeditor_uploader.fields import RichTextUploadingField


def current_date():
    return timezone.localdate ()


class Project (models.Model):
    users = models.ManyToManyField (User, blank=True, null=True)
    name = models.CharField (max_length=200)
    advisor = models.CharField (max_length=200)
    student_name = models.CharField (max_length=200)
    #student_email = models.EmailField(blank=True, unique=True)
    stage = models.CharField (max_length=50)
    description = models.CharField (max_length=5000)
    note = models.CharField (max_length=5000)

    # note = RichTextUploadingField()
    # note = HTMLField ()
    # note = RichTextField()
    # file = models.FileField(upload_to='upload', blank=True, null=True)
    # test=MDTextField()

    def __str__(self):
        return str (self.id)

    @property
    def professors(self):
        return self.users.filter (profile__role='professor')

    @property
    def students(self):
        return self.users.filter (profile__role='student')

        # @property
        # def file_name(self):
        #    if self.file:
        #        return self.file.name.split('/')[-1]
        #    return ''

        # @property
        # def file_url(self):
        #    if self.file:
        #        return self.file.url
        #    return ''


class Project2 (models.Model):
    name = models.CharField (max_length=50)
    advisor = models.CharField (max_length=200)
    stage = models.CharField (max_length=50)
    description = models.CharField (max_length=5000)
    note = models.CharField (max_length=5000)

    def __str__(self):
        return str (self.name)

# class ExampleModel(models.Model):
#    name = models.CharField(max_length=10000)
#    content = MDTextField()

professor_access/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

professor_access/views.py
import os

from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from django.forms import ModelForm

from professor_access.models import Project
from workflow.models import get_role
from .forms import LoginForm
from django.contrib.auth.decorators import user_passes_test


def professor_required(function):
    actual_decorator = user_passes_test (
        lambda u: get_role (u) == 'professor',
        login_url='/login/'
    )
    return actual_decorator (function)


class professorForm (ModelForm):
    class Meta:
        model = Project
        #fields = ['id', 'name', 'stage']

        fields = ['id', 'name', 'student_name','stage']
        #fields = ['id', 'name', 'student_name','student_email','stage']



@professor_required
def professor_list(request, template_name='professor_access/pa_list.html'):
    project = Project.objects.filter (users=request.user)
    data = {}
    data['object_list'] = project
    return render (request, template_name, data)


@professor_required
def professor_create(request, template_name='professor_access/project_form.html'):
    students = User.objects.filter (profile__role='student')
    professors = User.objects.filter (profile__role='professor')
    form = professorForm (request.POST or None)
    if form.is_valid ():
        project = form.save ()

        student_ids = request.POST.getlist('student_ids')
        for student_id in student_ids:
            student = User.objects.get (id=student_id)
            project.users.add (student)

        professor_ids = request.POST.getlist('professor_ids')
        for professor_id in professor_ids:
            professor = User.objects.get(id=professor_id)
            project.users.add(professor)

        project.users.add(request.user)

        project.user = request.user
        project.advisor = request.user.username
        project.save ()
        return redirect ('professor_access:pa_list')
    return render (request, template_name, locals ())


@professor_required
def detail(request, pk, template_name='professor_access/detail.html'):
    project = get_object_or_404 (Project, pk=pk)
    if request.method == 'POST':
        name = request.POST['name']
        stage = request.POST['stage']
        #description = request.POST['description']
        note = request.POST['note']

        project.name = name
        project.stage = stage
        #project.description = description
        project.note = note

        project.save ()
        return redirect ('professor_access:pa_list')

    return render (request, template_name, locals ())


@professor_required
def files(request, template_name='professor_access/files.html'):
    project = Project.objects.filter (user=request.user)
    data = {}
    data['object_list'] = project

    if request.method == 'POST':
        id = request.POST['id']
        file = request.FILES.get ('file')
        if file:
            project = Project.objects.get (id=id)
            project.file = file
            project.save ()
            return redirect ('professor_access/files')

    return render (request, template_name, data)


@professor_required
def upload(request, filename):
    path = os.path.join ('upload', filename)
    return HttpResponse (open (path, 'rb').read ())


class studentForm (ModelForm):
    class Meta:
        model = Project
        fields = ['id', 'name', 'advisor', 'stage']

professor_access/templates/professor_access/detail.html
{% extends "base.html" %}

{% block content %}
<link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">

<style>
	.box{
        display: none;

    }
     #subtitle {
        display: none;
    }
    a {
        color:black;
	    text-decoration: none;
    }

    a:hover {
        color:grey;
    }
    .box1{
        width:1030px;
        height:151px;
        border-color:#eee;
        background-color:#eee;
        border-style:none;
        margin:30px auto;
        padding:30px 15px;

    }
     #subtitle1{
        margin-top:80px;
        margin-bottom:30px;
        float:center;
        font-family:"Helvetia Neue","Helvetica";
        text-indent:350px;
        font-size:25px;
        line-height:60px;
        font-weight:none;


    }
	.input{
		display: none;
	}
	.submit{
		font-family:Arial;
		display: none;
		font-size:18px;
	}
	.return_home{
		color:red;
		text-align:right;
		font-size:18px;
	}
	.prj_name{
		text-align:center;
		font-size:30px;
		font-weight:bold;
		font-family:Arial;
	}
	.student_name{
		text-align:center;
		font-size:18px;
	}
	.text{
		 font-size:18px;
		 line-height: 2.5;
	}
	.name{
	    font-family:Arial;
		font-size:20px;
		font-weight:bold;
	}
	.line{
		margin: 20px;
	}

	.detail_content{
		width:1030px;
		margin: 10px auto;
		padding:10px;
	}
	.ql-container{
		height: 50vh;
	}
	.advisor_assistant{
		font-size:20;
		font-weight:bold;
	}
</style>

    <div class="box1"><a class= "title" href="/professor_access/" >Project Management System</a>

        <div id="subtitle1"><a href="/professor_access/">UNO Math Data Consulting Lab</a></div>
    </div>
<div class="detail_content">
	<!--<div class="return_home"><a href="{% url 'professor_access:pa_list' %}">Back to Home</a></div>-->
	<div class="return_home"><a href="/logout/">Logout</a>
	</div>
<form method="post" id="form">
{% csrf_token %}
<!--{{ form.media }}
	{{ form.as_p }}
	<!--<p>
		Project ID: {{project.id}}
	</p>-->
	<div class="prj_name">
		<span >{{project.name}}</span>
		<span class="input"><input type="text" name="name" value="{{project.name}}"></span><br />
	</div>
	<!--<div class="student_name">
		<br /><span>{{project.student_name}} <button type="button" class="edit">edit</button></span>
		<span class="input"><input type="text" name="student_name" value="{{project.student_name}}"></span>
	</div>-->
	<div class="student_name">
		<br /><span class="advisor_assistant">Advisor: </span>
		<span>{{ project.advisor }}</span>
		<!--<span class="input"><input type="text" name="student_name" value="{{project.student_name}}"></span>-->
	</div>
	<div class="student_name">
		<br /><span class="advisor_assistant">Student Assistant: </span>
		<span>{{ project.student_name }}</span>
		<!--<span class="input"><input type="text" name="student_name" value="{{project.student_name}}"></span>-->
	</div>
	<hr />
	
	<!--<p>
		Email:
		<span class="text">{{project.email}} <button type="button" class="edit">edit</button></span>
		<span class="input"><input type="text" name="email" value="{{project.email}}"></span>
	</p>-->

	<!--<p>
		Date:
		<span class="text">{{project.date|date:'m-d-Y'}} <button type="button" class="edit">edit</button></span>
		<span class="input"><input type="text" name="date" value="{{project.date|date:'Y-m-d'}}"></span>
	</p>-->
	<!--<div class="name">
		Content<button type="button" class="edit">edit</button>
	</div>
		<div class="text">{{project.description|safe}}</div>
		<div class="input">
			<input type="hidden" name="description" id="description">
			<div id ="editor1">{{project.description|safe}}</input></div>
		</div>

<!--{% autoescape off %}-->


	<div class="name">
		Content<button type="button" class="edit">edit</button>
	</div>
		<div class="text">{{project.note|safe}}</div>
		<div class="input">
			<input type="hidden" name="note" id="note">
			<div id="editor">{{project.note|safe}}</div>
		</div>
<!--{% endautoescape off %}-->

	<!--<p class="name">Picture<input type="file" name="file"></p>-->

	<div class="name">Stage</div>
		<span class="text">{{project.stage}} <button type="button" class="edit">edit</button></span>
	<span class="input"><input type="text" name="stage" value="{{project.stage}}"></span>


	<div class="submit">
		<input class="submit" type="submit" value="submit">
	</div>


</form>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>

<script>
	$('.edit').click(function(){
		$(this).parent().parent().find('.text').hide()
		console.log(this)
		console.log($(this).parent())
		$(this).parent().parent().find('.input').show()
		$('.submit').show()
	})

	var quill = new Quill('#editor', {
		theme: 'snow',
		modules: {
			toolbar: [
				[{ 'header': [1, 2, 3, 4, 5, 6, false] }],
				['bold', 'italic', 'underline'],        // toggled buttons
				['code-block'],
				[{ 'list': 'ordered'}, { 'list': 'bullet' }],
				[{ 'script': 'sub'}, { 'script': 'super' }],
				[{ 'indent': '-1'}, { 'indent': '+1' }],
				[{ 'color': [] }, { 'background': [] }],          
				[{ 'align': [] }, 'image', 'clean'],
			]
		}
	});

	$('#form').submit(function () {
		var html = quill.container.firstChild.innerHTML
		$('#note').val(html)
	})

	$('.edit1').click(function(){
		$(this).parent().parent().find('.text').hide()
		console.log(this)
		console.log($(this).parent())
		$(this).parent().parent().find('.input').show()
		$('.submit').show()
	})
	var quill1= new Quill('#editor1', {
		theme: 'snow',
		modules: {
			toolbar: [
				[{ 'header': [1, 2, 3, 4, 5, 6, false] }],
				['bold', 'italic', 'underline'],        // toggled buttons
				['code-block'],
				[{ 'list': 'ordered'}, { 'list': 'bullet' }],
				[{ 'script': 'sub'}, { 'script': 'super' }],
				[{ 'indent': '-1'}, { 'indent': '+1' }],
				[{ 'color': [] }, { 'background': [] }],
				[{ 'align': [] }, 'image', 'clean'],
			]
		}
	});

	$('#form').submit(function () {
		var html = quill1.container.firstChild.innerHTML
		$('#description').val(html)
	})
</script>


<div class="return_home"><a href="{% url 'professor_access:pa_list' %}">Back to Home</a></div>

	</div>
{% endblock %}

professor_access/templates/professor_access/detail2.html
{% extends "base.html" %}

{% block content %}
<html>
<header>
<style>
	.input{
		display: none;
	}
	.submit{
		display: none;
	}
	.back_button{
		text-align:right;
		font-size:18px;

	}
	.content_s{
		width:1030px;
		margin: 10px auto;
		padding:10px;
	}
	.prj_name{
		text-align:center;
		font-size:25px;
		font-weight:bold;
	}
	.professor_name{
		text-align:center;
		font-size:18px;
	}
	.text{
		 font-size:18px;
		 line-height: 2.5;
	}
	.name{
		font-size:18px;
		font-weight:bold;
	}
</style>
</header>
<body>
<div class="content_s">
<div class="back_button"><a href="{% url 'professor_access:sa_list' %}">Back to Home</a></div>

<form method="post">{% csrf_token %}

	<!--<p>
		Project ID: {{project.id}}
	</p>-->
	<p>
		<div class="prj_name">{{project.name}}</div>
		<span class="input"><input type="text" name="name" value="{{project.name}}"></span>
	</p>


	<div class="professor_name">
		<br /><div>{{project.advisor}}</div>
		<span class="input"><input type="text" name="advisor" value="{{project.advisor}}"></span>
	</div>

	<!--<p>
		Date:
		<span class="text">{{project.date|date:'m-d-Y'}} <button type="button" class="edit">edit</button></span>
		<span class="input"><input type="text" name="date" value="{{project.date|date:'Y-m-d'}}"></span>-->
	</p>
	<p class="name">Introduction</p>
{% autoescape off %}
		<span class="text">{{project.description|linebreaksbr}}</span>
		<span class="input"><textarea cols="40" rows="5" name="description">{{project.description}}</textarea></span>


	<p>
		<p class="name">Summary</p>
		<span class="text">{{project.note|linebreaksbr}}</span>
		<span class="input"><textarea cols="40" rows="5" name="note">{{project.note}}</textarea></span>
	</p>
	{% endautoescape %}
		<p class="name">
		Stage
		<span class="text">{{project.stage}} <button type="button" class="edit">edit</button></span>
		<span class="input"><input type="text" name="stage" value="{{project.stage}}"></span>
	</p>
	<p>
		<input class="submit" type="submit" value="submit">
	</p>

</form>



<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script>
	$('.edit').click(function(){
		$(this).parent().parent().find('.text').hide()
		$(this).parent().parent().find('.input').show()
		$('.submit').show()
	})

</script>
</div>

{% endblock %}
</body>
</html>

professor_access/templates/professor_access/pa_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}

<!--<a href="{% url 'student_access:sa_list' %}">Student Access</a>-->

<head>
    <title>Projects</title>
    <style>
     body {
        background-color: white;
        font-family: Arial, Helvetica, sans-serif;
        }
     .box{
        display: none;

    }
     #subtitle {
        display: none;
    }
    a {
        color:black;
	    text-decoration: none;
    }

    a:hover {
        color:grey;
    }
    .box1{
        width:1030px;
        height:151px;
        border-color:#eee;
        background-color:#eee;
        border-style:none;
        margin:30px auto;
        padding:30px 15px;

    }
     #subtitle1{
        margin-top:80px;
        margin-bottom:30px;
        float:center;
        font-family:"Helvetia Neue","Helvetica";
        text-indent:350px;
        font-size:25px;
        line-height:60px;
        font-weight:none;


    }
    .table {
        width:1030px;
        margin: left;
        /*border:2px solid black;
        border-spacing:0px;*/
        border-collapse: collapse;
        background-color:lightgrey;
        font-size:16px;
        font-family:Arial;
        line-height: 35px;
        margin: 30px auto;
        text-indent:10px;
    }

    td,th {
		border:2px solid black;
	}

	tr:nth-child(odd){
	     background-color:white;
	}

    tr:hover{
        background-color:darkgrey;
    }

    .hello{
        font-size: 20px;
        text-indent:460px;

    }
    /*.hello1{
        font-size: 20px;
        text-indent:300px;
    }*/
    .hello1{
        font-size:20px;
        width:1030px;
        margin: 10px auto;

    </style>
</head>

<body>
    <div class="box1"><a class= "title" href="/professor_access/" >Project Management System </a>
        <!--<div id = ""><a href="/logout/">Logout</a></div>-->
        <div id="subtitle1"><a href="/professor_access/">UNO Math Data Consulting Lab</a></div>
    </div>


<p class="hello1">
  Welcome to the Project Management System, there are some information about your projects.</br>

<!--<a href="{% url 'professor_access:project_new' %}">New Project</a>-->

</p>
<!--<h3>Project Information</h3>-->
<table class="table">
    <tr>
        <th>Project ID</th>
        <th>Project Name</th>
        <th>Student Assistant Name</th>
        <!--<th>advisor</th>-->
        <th>Stage</th>
        <th>Action</th>
        <!--<th>Action</th>-->
    </tr>
    {% for project in object_list %}

    <tr>
        <td>{{ project.id }}</td>
        <td>{{ project.name }}</td>
        <td>{{ project.student_name }}</td>
        <!--<td>{{ project.advisor }}</td>-->
        <td>{{ project.stage }}</td>
        <td><a href="{% url 'professor_access:detail' project.id %}">Details</a>
        <!--<td><a href="{% url 'professor_access:files'  %}">Upload</a></td>-->
        </td>
    </tr>
    {% endfor %}

    </tbody>
</table>
<p class="hello1">
<a href="{% url 'professor_access:project_new' %}">New Project</a>
</p>
</body>

{% endblock %}

professor_access/templates/professor_access/project_form.html
{% extends "base.html" %}

{% block content %}
<title>New Project</title>
<head>
    <style>
        .content{
            width:1030px;
            height:300px;
            border-color:#eee;
            border-style:none;
            margin:30px auto;
            padding:30px 15px;
        }
        .new_proj{
            font-size:28px;
            font-weight:bold;
		    text-align:center;

        }
        .content1{
            font-size:18px;
		    text-align:left;
        }
        .hello1{
            font-size:20px;
            width:1030px;
            margin: 10px auto;
        }
	    .return_home{
		    /*display:none;*/
		    text-align:right;
		    font-size:18px;
	        }


	}
    </style>

</head>
<div class="content">
<p class="hello2">
  Welcome to the Project Management System, you would create a new project here.</br>
</p>
<div class="new_proj">New Project</div>

    <div class="content1">
    <form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
    </form>
    </div>

    <div class="return_home">
        <a href="{% url 'professor_access:pa_list' %}">Back to Home</a>
    </div>
</div>

{% endblock %}

professor_access/templates/professor_access/sa_list.html
{% extends "base.html" %}

{% block content %}

<!--<a href="{% url 'student_access:sa_list' %}">Student Access</a>-->

<head>
    <title>Projects</title>
    <style>
        body {
            background-color: white;
            font-family: Arial, Helvetica, sans-serif;
            }

        .table {
            width:1030px;
            margin: left;
            /*border:2px solid black;
            border-spacing:0px;*/
            border-collapse: collapse;
            background-color:lightgrey;
            font-size:16px;
            line-height: 35px;
            margin: 30px auto;
            text-indent:10px;
                }

        td,th {
		    border:2px solid black;
	           }

	    tr:nth-child(odd){
	     background-color:white;
	            }

        tr:hover{
            background-color:darkgrey;
                }

        .hello1{
            font-size:20px;
            width:1030px;
            margin: 10px auto;
                }

   </style>
</head>

<body>

<p class="hello1">Welcome to the Project Management System, there are some information about your projects.</p>
<table class="table">
    <thead>
    <tr>
        <th>Project ID</th>
        <th>Project Name</th>
        <th>Advisor</th>
        <th>Stage</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>
    {% for project in object_list %}
    <tr>
        <td>{{ project.id}}</td>
        <td>{{ project.name }}</td>
        <td>{{ project.advisor }}</td>
        <td>{{ project.stage }}</td>
        <td><a href="{% url 'professor_access:detail2' project.id %}">Detail</a>
    </tr>
    <!--<li>{{ project.name }}  ({{ project.advisor }} ) ({{ project.email }} ) ({{ project.stage }} )
    </li>-->
    {% endfor %}
    </tbody>
</table>
</body>

{% endblock %}