admin_access/urls.py
from django.urls import path

from . import views

app_name = 'admin_access'

urlpatterns = [
  path('', views.admin_list, name='aa_list'),
  path ('new', views.admin_create, name='project_new'),
  path ('edit/<int:pk>', views.admin_update, name='project_edit'),
  path ('delete/<int:pk>', views.admin_delete, name='project_delete'),

]

datascicences/urls.py
from django.urls import include, path
from django.contrib import admin


from workflow import views

urlpatterns = [
    path ('accounts/', include ('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('student_access/', include('student_access.urls', namespace='student_access')),
    #path('student_access/login/', include ('student_access.urls', namespace='login')),
    path('professor_access/', include('professor_access.urls', namespace='professor_access')),
    path('admin_access/', include('admin_access.urls', namespace='admin_access')),
    path('', views.home),
    path('login/', views.login),
    path ('logout/', views.login),
    path('register/', views.register),

]

admin_access/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.conf import settings


class Project(models.Model):
    #project_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    user = models.ForeignKey (User, blank=True, null=True, on_delete=models.CASCADE, related_name='admin_project_set')
    name = models.CharField(max_length=50)
    permission = models.CharField (max_length=50)
    budget = models.CharField(max_length=200)
    stage = models.CharField(max_length=50)

    def __str__(self):
        #return str(self.project_id)
        return self.name

    def get_absolute_url(self):
        return reverse('admin_access:project_edit', kwargs={'pk': self.pk})

admin_access/views.py
from django.contrib.auth.models import User
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import ModelForm

from admin_access.models import Project
from workflow.models import get_role


def admin_required(function):
    actual_decorator = user_passes_test(
        lambda u: get_role(u) == 'admin',
        login_url='/login/'
    )
    return actual_decorator(function)


class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ['name', 'permission', 'budget', 'stage']


@admin_required
def admin_list(request, template_name='admin_access/aa_list.html'):
    if request.user.is_superuser:
        project = Project.objects.all()
    else:
        project = Project.objects.filter(user=request.user)
    data = {}
    data['object_list'] = project
    return render(request, template_name, data)

@admin_required
def admin_create(request, template_name='admin_access/project_form.html'):
    form = ProjectForm(request.POST or None)
    if form.is_valid():
        project = form.save(commit=False)
        project.user = request.user
        project.save()
        return redirect('admin_access:aa_list')
    return render(request, template_name, locals())

@admin_required
def admin_update(request, pk, template_name='admin_access/project_form.html'):
    if request.user.is_superuser:
        project= get_object_or_404(Project, pk=pk)
    else:
        project= get_object_or_404(Project, pk=pk, user=request.user)
    form = ProjectForm(request.POST or None, instance=project)
    if form.is_valid():
        form.save()
        return redirect('admin_access:aa_list')
    return render(request, template_name, {'form':form})

@admin_required
def admin_delete(request, pk, template_name='admin_access/project_confirm_delete.html'):
    if request.user.is_superuser:
        project= get_object_or_404(Project, pk=pk)
    else:
        project= get_object_or_404(Project, pk=pk, user=request.user)
    if request.method=='POST':
        project.delete()
        return redirect('admin_access:aa_list')
    return render(request, template_name, {'object':project})

admin_access/templates/admin_access/aa_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}

<head>
     <title>Projects</title>
    <style>
        body {
            background-color: white;
            font-family: Arial, Helvetica, sans-serif;
            }

        .table {
            width:1030px;
            margin: left;
            /*border:2px solid black;
            border-spacing:0px;*/
            border-collapse: collapse;
            background-color:lightgrey;
            font-size:16px;
            line-height: 35px;
            margin: 30px auto;
            text-indent:10px;
                }

        td,th {
		    border:2px solid black;
	           }

	    tr:nth-child(odd){
	        background-color:white;
	            }

        tr:hover{
            background-color:darkgrey;
                }

        .hello1{
            font-size:20px;
            width:1030px;
            margin: 10px auto;
                }
        .new_content{
            font-size:20px;
            width:1030px;
            margin: 10px auto;
            }

    </style>
</head>

<body>


<p class="hello1">Welcome to the Project Management System, there are some information about your project.</p>

<table class= "table">
    <thead>
    <tr>
        <th>Project Number</th>
        <th>Name</th>
        <th>Permission</th>
        <th>Budget</th>
        <th>Stage</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    {% for project in object_list %}

    <tr>
        <!--<td>{{ project.project_id }}</td>-->
        <td>{{ project.id }}</td>
        <td>{{ project.user }}</td>
        <td>{{ project.name }}</td>
        <td>{{ project.permission }}</td>
        <td>{{ project.budget }}</td>
        <td>{{ project.stage }}</td>
        <td><a href="{% url 'admin_access:project_edit' project.id %}">edit</a>
        <a href="{% url 'admin_access:project_delete' project.id %}">delete</a></td>
    </tr>
    <!--<li>{{ project.name }}  ({{ project.advisor }} ) ({{ project.email }} ) ({{ project.stage }} )
    </li>-->
    {% endfor %}
    </tbody>
</table>
<div class="new_content"><a href="{% url 'admin_access:project_new' %}">New</a></div>
</body>

{% endblock %}

admin_access/templates/admin_access/project_confirm_delete.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
<header>
    <style>
        .edit_content{
            width:1030px;
            margin: left;
            /*border:2px solid black;
            border-spacing:0px;*/
            border-collapse: collapse;
            font-size:16px;
            line-height: 35px;
            margin: 30px auto;
            text-indent:10px;
        }
    </style>
</header>
<div class="edit_content">
<h3><a href="{% url 'admin_access:aa_list' %}">Manage Projects</a>: Delete?</h3>

<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?<br/>
    <input type="submit" value="Delete" />
</form>
</div>
{% endblock %}

admin_access/templates/admin_access/project_form.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
<head>
     <title>Manage Projects</title>
    <style>
        .hello{
            font-size:20px;
            width:1030px;
            margin: 10px auto;
        }

        .edit_content{
            width:1030px;
            margin: left;
            /*border:2px solid black;
            border-spacing:0px;*/
            border-collapse: collapse;
            font-size:16px;
            line-height: 35px;
            margin: 30px auto;
            text-indent:10px;
        }

        /*.button{
            margin: 30px auto;
            text-indent:10px;
        }*/
    </style>
</head>

<body>

<p class="hello">Welcome to the Project Management System, there are some information about your project.</p>

<div class="edit_content">
<h2><a href="{% url 'admin_access:aa_list' %}">Manage Projects</a>: Edit</h2>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <div class="button"><input type="submit" value="Submit" /></div>
</form>
</div>
</body>
{% endblock %}